#!/usr/bin/env bash
# Build a release from the repo VERSION file:
#   1. stamp VERSION into the plugin header/constant, MCP package.json/package-lock.json and data meta.version
#   2. regenerate static artifacts (agent page, llms, OpenAPI, catalogs, web-root copies)
#   3. check every version matches, run the full test suite
#   4. write release/ranatec-api-<v>.zip, release/MANIFEST.md and release/ranatec-agentic-web-package-<v>.zip
#      (the package zip contains release/ranatec-api-<v>.zip and release/MANIFEST.md, so the installable
#       plugin zip is present after extraction)
# Usage: bash tools/release.sh
set -euo pipefail
cd "$(dirname "$0")/.."
V=$(tr -d '[:space:]' < VERSION)
[[ $V =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "VERSION must be x.y.z (got '$V')"; exit 1; }
echo "== Release $V"

# 1. stamp
sed -i -E "s/^( \* Version:[[:space:]]+).*/\1$V/" ranatec-api/ranatec-api.php
sed -i -E "s/define\('RANATEC_API_VERSION', '[^']*'\);/define('RANATEC_API_VERSION', '$V');/" ranatec-api/ranatec-api.php
python3 - "$V" <<'PY'
import json, sys, glob
v = sys.argv[1]
for f in ['ranatec-mcp/package.json']:
    d = json.load(open(f)); d['version'] = v; open(f, 'w').write(json.dumps(d, indent=2) + '\n')
f = 'ranatec-mcp/package-lock.json'; d = json.load(open(f)); d['version'] = v; d['packages']['']['version'] = v
open(f, 'w').write(json.dumps(d, indent=2) + '\n')
for f in glob.glob('ranatec-api/data/*.json'):
    d = json.load(open(f, encoding='utf-8')); d['meta']['version'] = v
    open(f, 'w', encoding='utf-8').write(json.dumps(d, indent=2, ensure_ascii=False) + '\n')
PY

# 2. regenerate
python3 tools/build_static.py >/dev/null

# 3. verify
python3 tools/check_versions.py >/dev/null || { python3 tools/check_versions.py; exit 1; }
bash tests/run-all.sh > /tmp/ranatec-release-tests.log 2>&1 || { grep -vE '^PASS' /tmp/ranatec-release-tests.log; echo "Tests failed — release aborted"; exit 1; }
TESTS=$(tail -1 /tmp/ranatec-release-tests.log)
echo "tests: $TESTS"

# 4. package
rm -f release/*.zip
mkdir -p release
zip -qr "release/ranatec-api-$V.zip" ranatec-api -x '*.DS_Store'
# MCP bundle for cPanel "Setup Node.js App" (e.g. Oderland): prebuilt dist/ + CommonJS startup file, no build step on the server
( cd ranatec-mcp && zip -qr "../release/ranatec-mcp-$V-cpanel.zip" package.json package-lock.json app.cjs dist .env.example )
PLUGIN_SHA=$(cd release && sha256sum "ranatec-api-$V.zip" "ranatec-mcp-$V-cpanel.zip")
write_manifest() {  # $1 = include package checksum line (yes/no)
cat > release/MANIFEST.md <<MD
# Ranatec Agentic Web package — release $V

Built from the ranatec.com crawl of 2026-10-06. Generated by \`tools/release.sh\` on $(date -u +%Y-%m-%d).
All component versions come from the repo \`VERSION\` file ($V) and are checked by \`tools/check_versions.py\`.

| File | What it is | How to use |
|---|---|---|
| \`release/ranatec-api-$V.zip\` | WordPress plugin: agent page, llms.txt, llms-full.txt, ai.txt, API catalogs, OpenAPI, REST API, product-quote + contact endpoints, daily sync | WordPress → Plugins → Add New → Upload → Activate → Settings → Permalinks → Save |
| \`release/ranatec-mcp-$V-cpanel.zip\` | MCP server, prebuilt (dist/ + app.cjs + package.json) for cPanel "Setup Node.js App" | Upload to the Node.js app root, Run NPM Install, startup file \`app.cjs\` (see docs/DEPLOYMENT-ODERLAND.md) |
| \`ranatec-agentic-web-package-$V.zip\` | Complete package: plugin source + **the plugin zip above** (in \`release/\`), MCP server source, web-root copies, robots.txt additions, build tools, tests, docs | Hand-over / archive; see README.md and docs/DEPLOYMENT.md inside |

## Component versions
| Component | Version |
|---|---|
| WordPress plugin (header + \`RANATEC_API_VERSION\`) | $V |
| OpenAPI \`info.version\` (plugin + web-root copies) | $V |
| API catalog \`X-package-version\`, agent page generator | $V |
| Data files \`meta.version\` | $V |
| MCP server (package.json; runtime \`/mcp/health\` reads package.json) | $V |

## SHA-256
\`\`\`
$PLUGIN_SHA
MD
if [[ $1 == yes ]]; then (cd release && sha256sum "ranatec-agentic-web-package-$V.zip") >> release/MANIFEST.md; fi
cat >> release/MANIFEST.md <<MD
\`\`\`
$( [[ $1 == yes ]] || echo '(The checksum of the complete-package zip cannot be stored inside that same zip; it is in the copy of MANIFEST.md next to the zip and in the git repository.)' )

## Checks
- \`python3 tools/check_versions.py\`: all components at $V
- \`bash tests/run-all.sh\`: $TESTS (PHP lint, JSON, contact + quote endpoints with and without mbstring, HTTP endpoints, version consistency, MCP end-to-end incl. runtime version)
- Crawl coverage: 262/262 sitemap URLs (9 cart/checkout/account pages skipped on purpose), 0 pending; 425 spec rows, 0 mismatches vs Firecrawl
MD
}
write_manifest no
zip -qr "release/ranatec-agentic-web-package-$V.zip" VERSION README.md docs ranatec-api ranatec-mcp web-root tools tests "release/ranatec-api-$V.zip" "release/ranatec-mcp-$V-cpanel.zip" release/MANIFEST.md \
  -x 'ranatec-mcp/node_modules/*' 'ranatec-mcp/dist/*' 'tools/.work/*' 'tools/__pycache__/*' '*.DS_Store'
write_manifest yes

# verify the archives
unzip -l "release/ranatec-agentic-web-package-$V.zip" | grep -q "release/ranatec-api-$V.zip" || { echo "plugin zip missing from package"; exit 1; }
unzip -l "release/ranatec-agentic-web-package-$V.zip" | grep -qE "node_modules|/dist/" && { echo "build output leaked into package"; exit 1; }
unzip -p "release/ranatec-api-$V.zip" ranatec-api/ranatec-api.php | grep -q "Version:           $V" || { echo "plugin zip has wrong version"; exit 1; }
unzip -p "release/ranatec-mcp-$V-cpanel.zip" package.json | grep -q "\"version\": \"$V\"" || { echo "MCP bundle has wrong version"; exit 1; }
unzip -l "release/ranatec-mcp-$V-cpanel.zip" | grep -q "dist/index.js" || { echo "MCP bundle missing dist/index.js"; exit 1; }
echo "== release/"; ls -la release
